### ISSUE TITLE
unknown signer type: S3Signer

### ISSUE THREAD

**Issue by Jovons** [jenshadlich/S3-Performance-Test#1]
Constants.S3_SIGNER is "S3Signer", and an exception "java.lang.IllegalArgumentException: unknown signer type: S3Signer". By changing it to "S3SignerType" the exception is gone.

**Comment by jenshadlich** [comment]
Hi Jovons,
please describe how you get this Exception. For me, everything works fine. Thanks.

**Comment by Jovons** [comment]
Hi, <aws-java-sdk.version>1.10.51</aws-java-sdk.version>  this version works if I have 
ClientConfiguration clientConfig = new ClientConfiguration();
clientConfig.setSignerOverride("S3SignerType");

without that configuration, a 400 request error shows. 

Or, without that configuration, but using 1.8 aws java sdk also works fine.

1.10 version + clientConfig.setSignerOverride("S3Signer") in your code raises an "unknown signer type" errror.

**Comment by jenshadlich** [comment]
Hi Jovons,
it took me a while to understand - it's not required to re-register `S3Signer.class` (where I used the `"S3Signer"` for). I changed it to `"S3SignerType"`. Thanks again.
