### ISSUE TITLE
Read works but upload fails 

### ISSUE THREAD

**Issue by rajholla** [jenshadlich/S3-Performance-Test#3]
Read works fine with the same access key and signature but upload doesn't work 

java.util.concurrent.ExecutionException: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: eca6e101-267c-495f-a3c8-b14fbac8a14d), S3 Extended Request ID: null

Running on windows machine. 
Is missing content type in objectMetadata is causing the problem ?

**Comment by jenshadlich** [comment]
Can you please provide how you call the program on the command line? What do you use as S3 endpoint?

**Comment by rajholla** [comment]
Thank you for the quick response 
Command line 
 java -jar s3pt.jar --endpointUrl ### --usePathStyleAccess true --accessKey ### --secretKey #### --bucketName blobstorepoc -n 1 --size 2048

End point is - internal Object storage[Cleversafe] which is compatible with the Amazon S3 

Any specific header we have to pass for ObjectMetadata ?

**Comment by rajholla** [comment]
Hello Jenshadlich,
After further analysis  I was able to find that,upload works fine with sdk version 1.10.77 or lower. 
Need to review the release notes for 1.11.0 to find what had changed.

**Comment by jenshadlich** [comment]
Hi rajholla,
the missing content type shouldn't be a problem. Unfortunately, I don't have access to a Cleversafe S3 endpoint (IBM Softlayer, right?).

You might try to explicitely set the signer:
```
--signerOverride VAL : override the S3 signer (e.g. 'S3Signer' or 'AWSS3V4Signer')
```
V2 signatures work, too (use the 'S3Signer').

In version 1.11.0 of the SDK, the signature V4 signing process because default in all regions.

**Comment by rajholla** [comment]
Hello Jenshadlich,
It worked as expected after changing the default behavior for signer. Thank you very much for your time.

**Comment by jenshadlich** [comment]
You are welcome :) Glad to hear that it worked.
